UI-MVC/Models/CreateTicketViewModel.cs
namespace SC.UI.Web.MVC.Models
{
    public class CreateTicketViewModel
    {
        public int AccId { get; set; }
        public string Problem { get; set; }
    }
}

UI-MVC/Models/ErrorViewModel.cs
using System;

namespace SC.UI.Web.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UI-MVC/Models/NewTicketResponseDTO.cs
namespace SC.UI.Web.MVC.Models
{
    public class NewTicketResponseDTO
    {
        public int TicketNumber { get; set; }
        public string ResponseText { get; set; }
        public bool IsClientResponse { get; set; }
    }
}

UI-MVC/Models/TicketResponseDTO.cs
using System;

namespace SC.UI.Web.MVC.Models
{
    public class TicketResponseDTO
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime Date { get; set; }
        public bool IsClientResponse { get; set; }
        public int TicketNumberOfTicket { get; set; }
    }
}

UI-MVC/Controllers/Api/TicketResponsesController.cs
using System.Linq;
using System.Net;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers.Api
{
    [ApiController]
    [Route("api/[controller]")]
    public class TicketResponsesController : ControllerBase
    {
        private readonly ITicketManager _mgr;

        public TicketResponsesController(ITicketManager mgr)
        {
            _mgr = mgr;
        }

        // GET: api/TicketResponses?ticketNumber=5
        [HttpGet()]
        public IActionResult Get(int ticketNumber)
        {
            var responses = _mgr.GetTicketResponses(ticketNumber);

            if (responses == null || !responses.Any())
                return NoContent(); //of: StatusCode(StatusCodes.Status204NoContent);

            return Ok(responses);
        }
        
        // POST: api/TicketResponse
        [HttpPost]
        public IActionResult Post(NewTicketResponseDTO response)
        {
            TicketResponse createdResponse = _mgr.AddTicketResponse(response.TicketNumber
                , response.ResponseText, response.IsClientResponse);

            if (createdResponse == null)
                return BadRequest("Er is iets misgelopen bij het registreren van het antwoord!");

            TicketResponseDTO responseData = new TicketResponseDTO()
            {
                Id = createdResponse.Id,
                Text = createdResponse.Text,
                Date = createdResponse.Date,
                IsClientResponse = createdResponse.IsClientResponse,
                TicketNumberOfTicket = createdResponse.Ticket.TicketNumber
            };
            return CreatedAtAction("Get", new { id = responseData.Id }, responseData);
        }
    }
}

UI-MVC/Controllers/Api/TicketsController.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;

namespace SC.UI.Web.MVC.Controllers.Api
{
    [ApiController]
    [Route("api/[controller]")]
    public class TicketsController : ControllerBase
    {
        private readonly ITicketManager _mgr;

        public TicketsController(ITicketManager mgr)
        {
            _mgr = mgr;
        }

        // PUT: api/Tickets/5/State/Closed
        [HttpPut("{id}/State/Closed")]
        public IActionResult PutTicketStateToClosed(int id)
        {
            Ticket ticket = _mgr.GetTicket(id);

            if (ticket == null)
                return NotFound();

            ticket.State = TicketState.Closed;
            _mgr.ChangeTicket(ticket);
            
            return NoContent();
        }

    }
}

UI-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UI-MVC/Controllers/TicketController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers
{
    public class TicketController : Controller
    {
        private readonly  ITicketManager _mgr;

        public TicketController(ITicketManager mgr)
        {
            _mgr = mgr;
        }
        
        // GET: /Ticket
        public IActionResult Index()
        {
            IEnumerable<Ticket> tickets = _mgr.GetTickets();
            return View(tickets);
        }
        
        // GET: /Ticket/Details/<ticket_number>
        public IActionResult Details(int id)
        {
            Ticket ticket = _mgr.GetTicket(id);
            
            if(ticket.Responses != null)
                ViewBag.Responses = ticket.Responses;
            else
                ViewBag.Responses = _mgr.GetTicketResponses(ticket.TicketNumber);
            
            return View(ticket);
        }
        
        // GET: /Ticket/Edit/<ticket_number>
        public IActionResult Edit(int id)
        {
            Ticket ticket = _mgr.GetTicket(id);
            return View(ticket);
        }
        // POST: /Ticket/Edit/<ticket_number>
        [HttpPost]
        public IActionResult Edit(int id, Ticket ticket)
        {
            if(!ModelState.IsValid)
                return View(ticket);
            
            _mgr.ChangeTicket(ticket);
            return RedirectToAction("Details", new {id = ticket.TicketNumber});
        }
        
        // GET: /Ticket/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: /Ticket/Create
        [HttpPost]
        public IActionResult Create(/*int accId, string problem*/CreateTicketViewModel createTicket)
        {
            Ticket newTicket = _mgr.AddTicket(/*accId*/createTicket.AccId, /*problem*/createTicket.Problem);
            return RedirectToAction("Details", new {id = newTicket.TicketNumber});
        }
        
        // GET: /Ticket/Delete/<ticket_number>
        public IActionResult Delete(int id)
        {
            Ticket ticket = _mgr.GetTicket(id);
            return View(ticket);
        }
        // POST: /Ticket/Delete/<ticket_number>
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            _mgr.RemoveTicket(id);
            return RedirectToAction("Index");
        }
    }
}

UI-MVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

UI-MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UI-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welkom";
}

@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>*@
<div class="jumbotron">
    <h1>SupportCenter</h1>
    <p>Welkom op het online helpdesk systeem.</p>
</div>

@*<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>*@
<div class="row">
    <div class="col-md-4">
        <h2>Nieuw ticket</h2>
        <p>Maak een nieuw ticket aan in het systeem.</p>
        <a class="btn btn-default" @*href="#"*@ asp-controller="Ticket" asp-action="Create">Nieuw ticket</a>
    </div>
    <div class="col-md-4">
        <h2>Alle tickets</h2>
        <p>Toont een lijst van alle bestaande tickets.</p>
        <a class="btn btn-default" @*href="#"*@ asp-controller="Ticket" asp-action="Index">Alle tickets</a>
    </div>
    <div class="col-md-4">
        <h2>Toon ticket</h2>
        <p>Geeft de details van één ticket.</p>
        @*<a class="btn btn-default" href="#">Toon ticket</a>*@
        <form asp-controller="Ticket" asp-action="Details" method="get" class="form-inline">
            <input name="id" type="number" placeholder="Ticketnummer" class="form-control"/>
            <input type="submit" value="Toon ticket" class="btn btn-default"/>
        </form>
    </div>
</div>

UI-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SupportCenter</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SupportCenter</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; SupportCenter</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

UI-MVC/Views/Ticket/Create.cshtml
@model SC.UI.Web.MVC.Models.CreateTicketViewModel

@{
    ViewBag.Title = "Ticket aanmaken";
}

<h2>Ticket aanmaken</h2>

<form asp-controller="Ticket" asp-action="Create" method="post">
    <div class="form-group">
        <label @*for="accId"*@asp-for="AccId">Account-id</label>
        <input @*id="accId" name="accId" type="number"*@asp-for="AccId" class="form-control"/>
    </div>
    <div class="form-group">
        <label @*for="problem"*@asp-for="Problem">Probleem</label>
        <input @*id="problem" name="problem" type="text"*@asp-for="Problem" class="form-control"/>
    </div>
    <input type="submit" value="Verzenden"/> | <a asp-action="Index">Annuleer</a>
</form>

UI-MVC/Views/Ticket/Delete.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Ticket verwijderen";
}

<h2>Ticket verwijderen</h2>
<p>Ben je zeker dat je onderstaand ticket wenst te verwijderen? </p>

@*<dl class="dl-horizontal">
    <dt>Id</dt><dd>@Model.TicketNumber</dd>
    <dt>Account</dt><dd>@Model.AccountId</dd>
    <dt>Probleem</dt><dd>@Model.Text</dd>
    <dt>Aangemaakt op</dt><dd>@Model.DateOpened</dd>
    <dt>Status</dt><dd>@Model.State</dd>
</dl>*@
<partial name="_TicketDetailsPartial" for="@Model"/>

<form asp-controller="Ticket" asp-action="DeleteConfirmed" asp-route-id="@Model.TicketNumber"  method="post">
    <input type="submit" value="Verwijderen"/> | <a asp-action="Index">Annuleer</a>
</form>

UI-MVC/Views/Ticket/Details.cshtml
@using SC.BL.Domain
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Ticket";
}

<h2>Ticket</h2>

@*<dl class="dl-horizontal">
    <dt>Id</dt><dd>@Model.TicketNumber</dd>
    <dt>Account</dt><dd>@Model.AccountId</dd>
    <dt>Probleem</dt><dd>@Model.Text</dd>
    <dt>Aangemaakt op</dt><dd>@Model.DateOpened</dd>
    <dt>Status</dt><dd>@Model.State</dd>
</dl>*@
<partial name="_TicketDetailsPartial" for="@Model"/>

<a asp-action="Edit" asp-route-id="@Model.TicketNumber">Bewerk</a> | <a asp-action="Index">Lijst</a>

<h3>Responses</h3>
<p><button class="btn btn-default" onclick="loadResponsesOfTicket(@Model.TicketNumber)">(Her)laad antwoorden</button></p>
<table id="responses" class="table">
    <tr>
        <th>Antwoord</th><th>Datum</th><th>Klant antwoord?</th>
    </tr>
    @foreach (TicketResponse response in (IEnumerable<TicketResponse>) ViewBag.Responses)
    {
        <tr>
            <td>@response.Text</td><td>@response.Date</td><td><input asp-for="@response.IsClientResponse" disabled/></td>
        </tr>
    }
</table>
<input id="responseText" name="responseText" type="text" style="margin-right: 5px" />
<button type="button" onclick="postResponse()">Verzenden</button>


@section Scripts
{
    <script type="text/javascript">
        // Toon responses
        function loadResponsesOfTicket(ticketNumber) {
            $.ajax('/api/TicketResponses?ticketnumber='+ticketNumber, {
                    type: 'GET',
                    dataType: 'json' // data-type expected back (response-data parsed to object)
                })
                .done(function (data) { showTicketResponses(data); })
                .fail(function () { alert('Oeps, something went wrong!'); });
        }
        function showTicketResponses(responses) {
            $('table#responses').find('tr:gt(0)').remove();
            setTimeout(function () {
                    responses.forEach(function (response) { addResponseToList(response); });
            }, 1000);
        }
        function addResponseToList(response) {
            var date = new Date(response.date);
            var checked = response.isClientResponse ? 'checked="checked"' : '';
            $('table#responses').append('<tr>'
                +'<td>'+response.text+'</td>'
                +'<td>'+date.toLocaleString()+'</td>'
                +'<td><input type="checkbox" disabled '+checked+'/></td>'
                +'</tr>');
        }
        
        // Voeg nieuw response toe
        function postResponse() {
            var ticketNumber = '@Model.TicketNumber';
            var answer = $('#responseText').val();
            if (answer) {
                var newResponse = { ticketNumber: ticketNumber, responseText: answer, 
                                    isClientResponse: false }
                $.ajax('/api/TicketResponses', { 
                        type: 'POST',
                        data: JSON.stringify(newResponse),
                        contentType : 'application/json',
                        dataType: 'json' // data-type expected back
                    })
                    .done(function (data) { addResponseToList(data); 
                        $('#responseText').val(''); })
                    .fail(function () { alert('Oeps, something went wrong!'); });
            }
        }
    </script>
}

UI-MVC/Views/Ticket/Edit.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Ticket wijzigen";
}

<h2>Ticket wijzigen</h2>

<form asp-controller="Ticket" asp-action="Edit" asp-route-id="@Model.TicketNumber" method="post">
    <div class="form-group">
        <label asp-for="TicketNumber">Id</label><input asp-for="TicketNumber" class="form-control" readonly/>
        <span asp-validation-for="TicketNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="AccountId">Account</label><input asp-for="AccountId" class="form-control"/>
        <span asp-validation-for="AccountId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Text">Probleem</label><input asp-for="Text" class="form-control"/>
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DateOpened">Aangemaakt op</label><input asp-for="DateOpened" class="form-control"/>
        <span asp-validation-for="DateOpened" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="State">Status</label>
        @* <input asp-for="State" class="form-control"/> *@
        <select asp-for="State" asp-items="@(new SelectList(Enum.GetValues(typeof(SC.BL.Domain.TicketState))))" class="form-control"></select>
        <span asp-validation-for="State" class="text-danger"></span>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="submit" value="Opslaan"/> | <a asp-action="Index">Annuleer</a>
</form>

UI-MVC/Views/Ticket/Index.cshtml
@model IEnumerable<SC.BL.Domain.Ticket>

@{
    ViewBag.Title = "Tickets";
}

<h2>Tickets</h2>

<p><a asp-action="Create">Nieuw ticket</a></p>

<table class="table">
    <tr>
        <th>Nummer</th>
        <th>Account</th>
        <th>Probleem</th>
        <th>Aangemaakt op</th>
        <th>Status</th>
        <th></th>
    </tr>
    @foreach (SC.BL.Domain.Ticket ticket in Model)
    {
        <tr>
            <td>@ticket.TicketNumber</td>
            <td>@ticket.AccountId</td>
            <td>@ticket.Text</td>
            <td>@ticket.DateOpened</td>
            <td>@ticket.State</td>
            <td>
                <a asp-action="Details" asp-route-id="@ticket.TicketNumber">Details</a>
                 | <a asp-action="Edit" asp-route-id="@ticket.TicketNumber">Bewerk</a>
                 | <a asp-action="Delete" asp-route-id="@ticket.TicketNumber">Verwijder</a>
            </td>
        </tr>
    }
</table>

UI-MVC/Views/Ticket/_TicketDetailsPartial.cshtml
@model SC.BL.Domain.Ticket

<dl class="dl-horizontal">
    <dt>Id</dt><dd>@Model.TicketNumber</dd>
    <dt>Account</dt><dd>@Model.AccountId</dd>
    <dt>Probleem</dt><dd>@Model.Text</dd>
    <dt>Aangemaakt op</dt><dd>@Model.DateOpened</dd>
    <dt>Status</dt>
    <dd>
        @*@Model.State*@
        <span id="state">@Model.State</span>
        @if (Model.State != SC.BL.Domain.TicketState.Closed)
        {
            <button type="button" onclick="closeTicket(@Model.TicketNumber)">Close</button>
        }
    </dd>
</dl>

<script type="text/javascript">
    function closeTicket(ticketNumber) {
        $.ajax('/api/Tickets/' + ticketNumber + '/State/Closed', {
                type: 'PUT'
            })
            .done(function (data) { $('#state').html('Closed'); })
            .fail(function () { alert('Oeps, something went wrong!'); });
    }
</script>